### PR TITLE
Fix `getY0` prop on AreaSeries

### PR DESCRIPTION
**Pull request by Pessimistress**
And other `*0` accessors

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
This is looking good! Would you mind writing a test documenting the thing you're fixing?

**Comment by mcnuttandrew** [comment]
🚨Stamped🚨

**Comment by Pessimistress** [comment]
@mcnuttandrew Any chance you can publish a patch today?

**Comment by mcnuttandrew** [comment]
I don't have that power, but you do, or @benshope does

**Pull request merged**
