### PR TITLE
Updated Highlight component

### PR DESCRIPTION
**Pull request by Domino987**
I improved the highlight component for additional Y zooming (which is one of your TODOs anyway) as a typescript file.
Needs my typescript definitions  from my other pull request xD

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
Interesting stuff! Would you mind rewriting the highlight component to be a regular javascript file? This is a javascript library, and while I totally support being friendly with typescript, we need to support our javascript users first.

**Comment by Domino987** [comment]
I wrote it on javascript and added right click dragging

**Comment by Domino987** [comment]
I also updated the zoom-able example to reflect the new highlight object

**Comment by mcnuttandrew** [comment]
See #938

**Pull request closed without merging**
