### PR TITLE
Updating peer dependencies to allow React 16

### PR DESCRIPTION
**Pull request by samhogg**
Hi!

Quick one liner so there aren't errors when upgrading to React 16 - from a quick poke around everything seems to be working

I haven't updated any of test harness yet, there's some work to do with Enzyme to get things going there.

### CODE REVIEW

**Comment by chrisirhc** [comment]
Don't see why not 👍

**Comment by samhogg** [comment]
Can we merge this, @chrisirhc?

**Comment by chrisirhc** [comment]
Yep, don't see why not. @jckr @Apercu any reservations?

**Comment by Apercu** [comment]
Yes I can, what's this newline at the end of the package though? :D

**Comment by Apercu** [comment]
`1.7.8`

**Comment by samhogg** [comment]
Thanks folks!

**Comment by Apercu** [comment]
Never mind, `1.7.9`

**Pull request merged**
