### PR TITLE
center sankey chart labels

### LINKED ISSUE #914: Sankey: labels not centered
Labels in Sankey chart aren't centered, relative to associated rectangle.

For example, in docs site
screen shot 2018-08-20 at 11 35 31 am
screen shot 2018-08-20 at 11 35 37 am
The position of `Road Transport`(far right) is off, and it's not clear which rectangle `Solar`(bottom left) is associated with.

### PR DESCRIPTION
**Pull request by zachguo**
fix #914 

before:
screen shot 2018-08-20 at 1 41 44 pm

after:
screen shot 2018-08-20 at 1 41 28 pm

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
Looks good!

**Comment by zachguo** [comment]
@mcnuttandrew @benshope could you please tell me when you are going to release a new version?

**Comment by benshope** [comment]
@zachguo I could bump another patch quickly if necessary - but are you able to `npm install git://github.com/uber/react-vis.git#master --save` if you need the very latest?

**Comment by zachguo** [comment]
If you have time, a quick patch release would be wonderful! Thanks in
advance. We use react-vis in production, so semver is preferred.

**Comment by benshope** [comment]
@zachguo yea I guess no harm in that, bumped a patch

**Comment by zachguo** [comment]
@benshope thank you, but the v1.10.6 **npm** package doesn't contain these changes. Github release does.
screen shot 2018-08-23 at 3 05 35 pm

**Comment by zachguo** [comment]
@benshope Never mind. I can wait, thank you!

BTW, It's pretty strange that when I ran `npm i git+ssh://git@github.com:uber/react-vis.git#1.10.6` I got an empty package.
```
$ tree node_modules/react-vis/
node_modules/react-vis/
├── CHANGELOG.md
├── LICENSE
├── README.md
└── package.json

0 directories, 4 files

$ cat node_modules/react-vis/package.json | grep _id
  "_id": "react-vis@1.10.6",
```

**Pull request merged**
