### PR TITLE
Upgrade docs

### PR DESCRIPTION
**Pull request by mcnuttandrew**

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
This PR upgrades the docs, normally i'd just upgrade them directly but i'm pretty unfamiliar with ocular so i'd appreciate a second pairs of eyes

**Comment by balthazar** [comment]
Looks like it created a sub directory `dist` inside `dist`, which I don't think is right. Did you managed to get the showcases with link to work?

**Comment by balthazar** [comment]
Publishing with your fix

**Comment by mcnuttandrew** [comment]
The showcases are kinda weird and I don't think they need to be withLinked, like all of the components within them already have withLinks so it seemed redundant?

**Comment by balthazar** [comment]
Yeah don't need to

**Pull request closed without merging**
