### PR TITLE
Fix broken link in readme

### PR DESCRIPTION
**Pull request by samhogg**
The examples folder has moved, pointed the link to the correct directory in the repo

😊

### CODE REVIEW

**Comment by amilajack** [comment]
LGTM

**Comment by Apercu** [comment]
Waiting for Sam to sign the CLA

**Comment by samhogg** [comment]
@Apercu CLA signed, not sure why the bot hasn't updated.

**Comment by Apercu** [comment]
Ok thanks then! 😄

**Comment by amilajack** [comment]
Did you make the change from github's built-in editor? If you did, GitHub will make the PR on behalf of an email like sam@noreply.github.com or something like that (for security reasons
)

**Comment by samhogg** [comment]
Ahhh, yes, that's probably the reason.

**Pull request merged**
