### PR TITLE
Fix style assignment error by removing spread in AxisTitle

### LINKED ISSUE #439: Style assignment error in Firefox
Just discovered this during browser testing - Chrome doesn't worry but we have issues with Firefox (v53), it won't even render the examples.

`TypeError: CSS2Properties doesn't have an indexed property setter for '0'`

Fix incoming, [I've narrowed it down to spreading the text anchor property in `AxisTitle`](https://github.com/uber/react-vis/blob/master/src/plot/axis/axis-title.js#L83)

### PR DESCRIPTION
**Pull request by samhogg**
Fixes #439

### CODE REVIEW

**Comment by samhogg** [comment]
@mcnuttandrew incoming.

**Comment by samhogg** [comment]
@mcnuttandrew added some assertions 😄

**Comment by mcnuttandrew** [comment]
Wow! Love it. Ill merge it in as soon as travis get's done

**Comment by samhogg** [comment]
@mcnuttandrew just rebased and the build broke, nothing to do with my code though - would love to get this in ASAP as it's blocking release for us.

**Pull request merged**
