### PR TITLE
Expose `className` prop on Crosshair component and update docs

### PR DESCRIPTION
**Pull request by jonsadka**
For apps that use inline styles, the cross does not get positioned correctly because the crosshair is positioned absolutely. Expose `className` on this component so that applications using inline styles can hook into this component

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
Looks good! Maybe add a test?

**Comment by jonsadka** [comment]
@mcnuttandrew tests added

**Comment by mcnuttandrew** [comment]
I don't know why coveralls would have failed like that, maybe re-run the build?

**Comment by jonsadka** [comment]
Yeah weird. Rebuilding travis

**Comment by jonsadka** [comment]
@mcnuttandrew do you know what I need to do to get a new coverage report? I tried rebuilding both builds in travis but no change

**Comment by mcnuttandrew** [comment]
that's super weird, i don't know why that would be? maybe ask @balthazar  i think he set that system up and might have some insight?

**Comment by jonsadka** [comment]
@mcnuttandrew all fixed. There was a `.only(` hanging out. Stamped?

**Comment by jonsadka** [comment]
# 😊

**Pull request merged**
