### PR TITLE
Implementing mouse Enter and Leave events on DiscreteColorLegend component

### PR DESCRIPTION
**Pull request by murilobast**
This PR implements mouseEnter and mouseLeave events to DiscreteColorLegend component making legends behavior more complex and adds more customization options to the component behavior.

Usage:
```javascript
<DiscreteColorLegend
	items={...}
	onItemMouseEnter={(item, index, event) => ...}
	onItemMouseLeave={(item, index, event) => ...}
/>
```

Thanks!

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
Nb: the way we generally write tests is to add an example, and then write tests against that. That way we the developers can interact with the feature as we are developing it (on the showcase page) and we have continuous verification that all is in working order.

**Comment by murilobast** [comment]
@mcnuttandrew 
Sure, man.
Just added sume documentation on those tho mouse handlers. Is the anything else I should write?

Thanks in advance

**Comment by mcnuttandrew** [comment]
nope, nothing else needed! your doin a great job so far

**Comment by murilobast** [comment]
Sorry about the delay, but I couldn't write the test for the implemented feature, since I`m not familiar to writing tests and I didn't find a test which I could base myself with.
I'd be glad to have some help/tips.

Thanks =]

**Comment by mcnuttandrew** [comment]
Hey @murilobast I branched your PR and opened another one, I didn't mean to step on any toes, I just figured it would be a little better than letting it get squandered?

**Pull request closed without merging**
