### PR TITLE
Decorative Slope generation incorrect when slope is vertical

### PR DESCRIPTION
**Pull request by mcnuttandrew**
Addresses #497

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
I'm 100% sure the tests will pass on this once #505 lands

**Comment by mcnuttandrew** [comment]
bump for review?

**Comment by mcnuttandrew** [comment]
review?

**Comment by mcnuttandrew** [comment]
@Apercu now that this is merged in, would you mind cutting v1.7.0 to go along with the version reference in the suite release blog post?

**Comment by Apercu** [comment]
Yep, done ;)

**Pull request merged**
