### PR TITLE
Add a module build

### PR DESCRIPTION
**Pull request by salzhrani**

### CODE REVIEW

**Comment by salzhrani** [comment]
Agreement signed

**Comment by dignifiedquire** [comment]
Any chance this could get merged and published, this would be very useful for us

**Comment by Apercu** [comment]
Hey, Thank you for this and very sorry for the delay! 😭 
I've went ahead and rebased your commit against master on the [module](https://github.com/uber/react-vis/tree/module) branch and will merge once the tests clears. I'll close this PR once this is done, but you will still be the commit author .

**Comment by Apercu** [comment]
Merged to master in https://github.com/uber/react-vis/commit/2502ffeffababebdbd830a1e8520f428b0fef7d3 and deployed in `1.6.4`. Please do not hesitate to report any issue/feedback.

**Pull request closed without merging**
