### PR TITLE
A case is wrong in HInt.js

### PR DESCRIPTION
**Pull request by gwokae**
A case in Hint.js on `_mapOrientationToAlign` is wrong.

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
This looks fine. After you sign the CLA can you bump again to make the checks pass?

**Comment by Apercu** [comment]
This bot using the committer rather than the author is a bit annoying. @gwokae would you be able to amend?

**Comment by gwokae** [comment]
@Apercu I'm not able to amend from github. Can you give me some instruction ? (push an empty commit? )

**Comment by mcnuttandrew** [comment]
Just push an empty commit for the bot to re-triggger

**Comment by gwokae** [comment]
@mcnuttandrew  just pused an empty commit 😀

**Comment by Apercu** [comment]
Thanks!

**Pull request merged**
