### PR TITLE
Upgrade all d3 modules to 1.0

### PR DESCRIPTION
**Pull request by bulyonov**
This PR upgrades all d3 modules to 1.0 or later. 

*Note*: currently d3 modules don't support `import` so currently `require` is used.

### CODE REVIEW

**Comment by chrisirhc** [comment]
Does this fix #114 ?

**Comment by chrisirhc** [comment]
How come they don't support `import`? Isn't `import` backward compatible? What error are you seeing when you use it?

**Comment by ibgreen** [comment]
@chrisirhc 
> How come they don't support import?

Looks like d3 v4 is not compatible with babel import at the moment.
https://github.com/d3/d3/issues/2733

**Comment by bulyonov** [comment]
Since there's no possibility import defaults in d3 modules, I'm importing all of the functions from the module. We should make a second pass to clean up the imports later.

**Pull request merged**
