### PR TITLE
Added Typedefinitions for Typescript

### PR DESCRIPTION
**Pull request by Domino987**

### CODE REVIEW

**Comment by mcnuttandrew** [comment]
There's a lot of copy and pasted content in there, is it possible to make this be programmatically generated?

**Comment by Domino987** [comment]
The fastest way would probably be to write a small script. I will look into it.

**Comment by Domino987** [comment]
I wrote a script to exchange the anys from the definitions to the type value.
If you take a look at it and check if it could be merged to the master branch.

**Comment by mcnuttandrew** [comment]
I'm not seeing this script that you are referencing? Am I missing something?

**Comment by Domino987** [comment]
I wrote it in python but the definition file is the new one so it is already executed. But I can upload it if that helps.

**Comment by mcnuttandrew** [comment]
My interest in asking for a script to automatically assemble the type definitions is that we want to make sure that everything stays up to date. So it might be good to build node or bash script that can be part of the library and can be executed periodically to generate the definition files.

**Comment by evgsil** [comment]
I've created such kind of script. It uses prop-types as source for automated type definitions generation. https://github.com/evgsil/react-vis-typings

**Comment by mcnuttandrew** [comment]
@evgsil that looks super cool! i'd be delighted to see PR bringing that script into the library

**Comment by medington** [comment]
Is there any reason that this PR should not be closed in favor of the work being done in #1003 ?

**Pull request closed without merging**
